udistrital/plan_anual_auditoria_mf

.editorconfig, .gitignore, src/app/app.component.ts, tsconfig.json
udistrital/sisifo_documentacion#128
=> fix: solucion de conflictos udistrital/sisifo_documentacion#128

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/modules/consulta-plan-anual-auditoria/consulta-plan-anual-auditoria.component.html, src/app/modules/consulta-plan-anual-auditoria/consulta-plan-anual-auditoria.component.ts, src/app/modules/editar-actividades/editar-actividades.component.css, src/app/modules/editar-actividades/editar-actividades.component.html, src/app/modules/editar-actividades/editar-actividades.component.spec.ts, src/app/modules/editar-actividades/editar-actividades.component.ts, src/app/modules/editar-actividades/editar-actividades.module.ts, src/app/modules/gestion-auditoria/gestion-auditoria.module.ts
udistrital/sisifo_documentacion#187
=> feat:  pruebas de conexion con microcliente de formularios dinamicos udistrital/sisifo_documentacion#187

src/app/modules/consulta-plan-anual-auditoria/consulta-plan-anual-auditoria.component.ts, src/app/modules/editar-actividades/editar-actividades.component.html, src/app/modules/editar-actividades/editar-actividades.component.ts
udistrital/sisifo_documentacion#195
=> fix: Cambio en URLs de conexión con microcliente de formularios dinamicos 

package-lock.json, src/app/app.module.ts, src/app/modules/cargar-archivo/cargar-archivo.component.css, src/app/modules/cargar-archivo/cargar-archivo.component.html, src/app/modules/cargar-archivo/cargar-archivo.component.spec.ts, src/app/modules/cargar-archivo/cargar-archivo.component.ts, src/app/modules/cargar-archivo/cargar-archivo.module.ts, src/app/modules/consulta-plan-anual-auditoria/consulta-plan-anual-auditoria.component.ts, src/app/modules/formulario-auditoria-especial/formulario-auditoria-especial.component.css, src/app/modules/gestion-auditoria/registro-plan-anual-auditoria/registro-plan-anual-auditoria.component.html, src/app/modules/gestion-auditoria/registro-plan-anual-auditoria/registro-plan-anual-auditoria.component.ts, src/app/services/modal.service.ts
udistrital/sisifo_documentacion#196
=> feat: Implementación funcionalidad de los botones y modales PAA

src/app/managers/errorManager.ts, src/app/managers/requestManager.ts, src/app/modules/cargar-archivo/cargar-archivo.component.html, src/app/modules/cargar-archivo/cargar-archivo.component.ts, src/app/modules/cargar-archivo/cargar-archivo.module.ts, src/app/services/gestor-documental.service.ts, src/environments/environment.development.ts, src/environments/environment.ts
udistrital/sisifo_documentacion#200
=> feat: Integracion cargue pdf al gestor documental

angular.json, package-lock.json, package.json, src/app/app.module.ts, src/app/components/formulario-dinamico/formulario-dinamico.component.css, src/app/components/formulario-dinamico/formulario-dinamico.component.html, src/app/components/formulario-dinamico/formulario-dinamico.component.spec.ts, src/app/components/formulario-dinamico/formulario-dinamico.component.ts, src/app/data/forms/formulario-quemado.ts, src/app/data/models/formulario.model.ts, src/app/modules/cargar-archivo/cargar-archivo.component.ts, src/app/modules/gestion-auditoria/gestion-auditoria.component.html, src/app/modules/gestion-auditoria/gestion-auditoria.component.ts, src/app/modules/gestion-auditoria/gestion-auditoria.module.ts
udistrital/sisifo_documentacion#223
=> feat: Implementación formulario dinamico udistrital/sisifo_documentacion#223

src/app/modules/cargar-archivo/cargar-archivo.component.ts, src/app/modules/gestion-auditoria/registro-plan-anual-auditoria/registro-plan-anual-auditoria.component.html, src/app/modules/gestion-auditoria/registro-plan-anual-auditoria/registro-plan-anual-auditoria.component.ts, src/app/services/lambda.service.ts, src/environments/environment.development.ts, src/environments/environment.ts
udistrital/sisifo_documentacion#228
=> feat: Se implementa el cargue masivo con lambda y se ajustan los botones para recibir los archivos especificos

src/environments/environment.development.ts, src/environments/environment.ts
udistrital/sisifo_documentacion#234
=> feat: Se elimina la variable de entorno LAMBDA_SERVICE de environment

src/app/app.module.ts, src/app/data/forms/formulario-PAA-valores.ts, src/app/modules/programacion/consulta-plan-anual-auditoria/consulta-plan-anual-auditoria.component.html, src/app/modules/programacion/consulta-plan-anual-auditoria/consulta-plan-anual-auditoria.component.ts, src/app/modules/programacion/consulta-plan-anual-auditoria/consulta-plan-anual-auditoria.module.ts, src/app/modules/programacion/registrar-auditorias/add-auditoria-modal/add-auditoria-modal.component.html, src/app/modules/programacion/registrar-auditorias/add-auditoria-modal/add-auditoria-modal.component.ts, src/app/modules/programacion/registrar-auditorias/registrar-auditorias.component.ts, src/app/modules/programacion/registrar-auditorias/registrar-auditorias.module.ts, src/app/modules/programacion/registrar-plan/registrar-plan.component.ts, src/app/services/plan-anual-auditoria.service.ts, src/environments/environment.development.ts, src/environments/environment.ts
udistrital/sisifo_documentacion#237
=> feat: Integración microcliente y microservicio CRUD para registro de plan anual de auditoría

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/data/models/parametros/parametros.ts, src/app/data/models/plan-anual-auditoria/plan-anual-auditoria.ts, src/app/modules/programacion/consulta-plan-anual-auditoria/consulta-plan-anual-auditoria.component.ts, src/app/modules/programacion/registrar-auditorias/add-auditoria-modal/add-auditoria-modal.component.html, src/app/modules/programacion/registrar-auditorias/add-auditoria-modal/add-auditoria-modal.component.ts, src/app/modules/programacion/registrar-auditorias/registrar-auditorias.component.html, src/app/modules/programacion/registrar-auditorias/registrar-auditorias.component.ts, src/app/modules/programacion/registrar-plan/registrar-plan.component.html, src/app/modules/programacion/registrar-plan/registrar-plan.component.ts, src/app/modules/programacion/revision-jefe/revision-jefe.component.ts, src/app/modules/programacion/revision-jefe/revision-jefe.module.ts, src/app/modules/programacion/revision-jefe/revision-jefecomponent.spec.ts, src/app/services/plan-anual-auditoria.service.ts
udistrital/sisifo_documentacion#251
=> feat: Integración microcliente y microservicio CRUD para registro del plan anual de auditoría - Parte 2

src/app/modules/cargar-archivo/cargar-archivo.component.ts, src/app/modules/programacion/registrar-auditorias/registrar-auditorias.component.html, src/app/modules/programacion/registrar-auditorias/registrar-auditorias.component.ts, src/environments/environment.development.ts, src/environments/environment.ts
udistrital/sisifo_documentacion#281
=> feat: Se agrega el id del plan de auditoria al modal de cargue masivo

src/app/modules/programacion/registrar-auditorias/registrar-auditorias.component.html
udistrital/sisifo_documentacion#284
=> fix: se corrige boton ver para presentacion udistrital/sisifo_documentacion#284

src/app/modules/programacion/auditorias-especiales/auditorias-especiales.component.html, src/app/modules/programacion/auditorias-especiales/auditorias-especiales.component.ts, src/app/modules/programacion/auditorias-especiales/formulario-auditoria-especial/formulario-auditoria-especial.component.html, src/app/modules/programacion/auditorias-especiales/formulario-auditoria-especial/formulario-auditoria-especial.component.ts
udistrital/sisifo_documentacion#282
=> feat: Integracion del crud para crear y editar las auditorias especiales. 

src/_guards/auth.guard.ts, src/app/app-routing.module.ts, src/app/core/services/implicit_autentication.service.ts, src/app/modules/programacion/components/consulta-plan-auditoria/consulta-plan-auditoria.component.html, src/app/modules/programacion/components/consulta-plan-auditoria/consulta-plan-auditoria.component.ts, src/app/modules/programacion/components/consulta-plan-auditoria/registrar-auditorias/add-auditoria-modal/add-auditoria-modal.component.ts, src/app/modules/programacion/components/consulta-plan-auditoria/registrar-auditorias/registrar-auditorias.component.ts, src/app/modules/programacion/components/consulta-plan-auditoria/registrar-plan/registrar-plan.component.ts, src/app/shared/components/cargar-archivo/cargar-archivo.component.ts, src/environments/environment.ts
udistrital/sisifo_documentacion#254
=> feat: Implementación manejo de roles módulo de programación 

src/app/modules/programacion/components/consulta-plan-auditoria/consulta-plan-auditoria.component.ts, src/app/modules/programacion/components/consulta-plan-auditoria/registrar-auditorias/add-auditoria-modal/add-auditoria-modal.component.ts, src/app/modules/programacion/components/consulta-plan-auditoria/registrar-auditorias/registrar-auditorias.component.ts, src/app/shared/data/models/plan-anual-auditoria/plan-anual-auditoria.ts, src/environments/environment.ts
udistrital/sisifo_documentacion#303
=> refactor: ajustes en la muestra de los datos obtenidos por el plan_mid

src/app/core/services/autenticacion-mid.service.ts, src/app/modules/programacion/components/asignar-auditorias/asignar-auditorias.component.html, src/app/modules/programacion/components/asignar-auditorias/asignar-auditorias.component.ts, src/app/modules/programacion/components/asignar-auditorias/modal-agregar-auditor/modal-agregar-auditor.component.html, src/app/modules/programacion/components/asignar-auditorias/modal-agregar-auditor/modal-agregar-auditor.component.spec.ts, src/app/modules/programacion/components/asignar-auditorias/modal-agregar-auditor/modal-agregar-auditor.component.ts, src/app/modules/programacion/components/auditorias-especiales/formulario-auditoria-especial/formulario-auditoria-especial.component.ts, src/app/modules/programacion/components/auditorias-especiales/registro-auditorias-especiales.component.ts, src/app/modules/programacion/programacion.module.ts, src/environments/environment.ts
udistrital/sisifo_documentacion#285
=> feat: Se realiza la integracion de asignación de auditores 

src/app/modules/programacion/components/consulta-plan-auditoria/consulta-plan-auditoria.component.html, src/app/modules/programacion/components/consulta-plan-auditoria/consulta-plan-auditoria.component.ts, src/app/modules/programacion/components/consulta-plan-auditoria/registrar-auditorias/registrar-auditorias.component.ts, src/app/modules/programacion/programacion.module.ts
udistrital/sisifo_documentacion#310
=> feat: Implementación registro de organización de auditorías con drag and drop

src/app/modules/programacion/components/asignar-auditorias/modal-agregar-auditor/modal-agregar-auditor.component.html, src/app/modules/programacion/components/auditorias-especiales/formulario-auditoria-especial/formulario-auditoria-especial.component.html, src/app/modules/programacion/components/auditorias-especiales/formulario-auditoria-especial/formulario-auditoria-especial.component.ts, src/app/shared/elements/components/cargar-archivo/cargar-archivo.component.ts, src/app/shared/modules/material.module.ts, src/app/shared/services/modal.service.ts, src/assets/styles/sweetalert.scss
udistrital/sisifo_documentacion#306
=> feat: Se agrega el checkbox para el auditor principal, selección de auditores y su registro

src/app/modules/programacion/components/consulta-plan-auditoria/consulta-plan-auditoria.component.ts
udistrital/sisifo_documentacion#312
=> fix: solución error de estdos consulta-plan 

src/app/modules/planeacion/components/auditorias-internas/tabla-auditorias-internas/tabla-auditorias-internas.component.css, src/app/modules/planeacion/components/auditorias-internas/tabla-auditorias-internas/tabla-auditorias-internas.component.html, src/app/modules/planeacion/components/auditorias-internas/tabla-auditorias-internas/tabla-auditorias-internas.component.ts, src/app/modules/planeacion/components/auditorias-internas/tabla-auditorias-internas/tabla-auditorias-internas.utilidades.ts, src/app/modules/programacion/components/consulta-plan-auditoria/modal-lista-rechazos/modal-lista-rechazos.component.html, src/app/shared/elements/components/dialogs/modal-ver-documento/modal-ver-documento.component.css, src/app/shared/elements/components/dialogs/modal-ver-documento/modal-ver-documento.component.html, src/app/shared/elements/components/dialogs/modal-ver-documento/modal-ver-documento.component.spec.ts, src/app/shared/elements/components/dialogs/modal-ver-documento/modal-ver-documento.component.ts, src/app/shared/elements/templates/plantilla-modal/plantilla-modal.component.css, src/app/shared/elements/templates/plantilla-modal/plantilla-modal.component.html, src/app/shared/elements/templates/plantilla-modal/plantilla-modal.component.ts, src/app/shared/shared.module.ts, src/assets/styles/estilos-generales.scss, src/environments/environment.ts
feat: udistrital/sisifo_documentacion#321 Integración de la plantilla plan trabajo a la vista
=> feat: Integración de la plantilla plan trabajo a la vista

src/app/modules/programacion/components/consulta-plan-auditoria/consulta-plan-auditoria.component.html, src/app/modules/programacion/components/consulta-plan-auditoria/consulta-plan-auditoria.component.ts, src/app/modules/programacion/components/consulta-plan-auditoria/modal-ver-documentos-plan/modal-ver-documentos-plan.component.css, src/app/modules/programacion/components/consulta-plan-auditoria/modal-ver-documentos-plan/modal-ver-documentos-plan.component.html, src/app/modules/programacion/components/consulta-plan-auditoria/modal-ver-documentos-plan/modal-ver-documentos-plan.component.spec.ts, src/app/modules/programacion/components/consulta-plan-auditoria/modal-ver-documentos-plan/modal-ver-documentos-plan.component.ts, src/app/modules/programacion/components/consulta-plan-auditoria/registrar-auditorias/registrar-auditorias.component.html, src/app/modules/programacion/components/consulta-plan-auditoria/registrar-auditorias/registrar-auditorias.component.ts, src/app/modules/programacion/components/consulta-plan-auditoria/registrar-plan/registrar-plan.component.html, src/app/modules/programacion/components/consulta-plan-auditoria/registrar-plan/registrar-plan.component.ts, src/app/modules/programacion/programacion.module.ts
udistrital/sisifo_documentacion#320
=> feat: Implementación visualización de formulario desde el rol auditor

src/app/core/services/plan-anual-auditoria.service.ts, src/app/modules/programacion/components/auditorias-especiales/formulario-auditoria-especial/formulario-auditoria-especial.component.ts, src/app/modules/programacion/components/auditorias-especiales/registro-auditorias-especiales.component.html, src/app/modules/programacion/components/auditorias-especiales/registro-auditorias-especiales.component.ts, src/app/modules/programacion/components/consulta-plan-auditoria/consulta-plan-auditoria.component.html, src/app/modules/programacion/components/consulta-plan-auditoria/consulta-plan-auditoria.component.ts, src/app/shared/data/models/plan-anual-auditoria/plan-anual-auditoria.ts
udistrital/sisifo_documentacion#318
=> feat: Integracion de actualización y eliminación de auditores

src/app/modules/programacion/components/consulta-plan-auditoria/consulta-plan-auditoria.component.html, src/app/modules/programacion/components/consulta-plan-auditoria/consulta-plan-auditoria.component.ts
udistrital/sisifo_documentacion#326
=> feat: Se implementa la paginacion en la consulta del paa

src/app/modules/programacion/components/consulta-plan-auditoria/registrar-plan/registrar-plan.component.css, src/app/modules/programacion/components/consulta-plan-auditoria/registrar-plan/registrar-plan.component.html, src/app/modules/programacion/components/consulta-plan-auditoria/registrar-plan/registrar-plan.component.ts
udistrital/sisifo_documentacion#338 Interfaz ver plan de acción
=> feat: Interfaz ver plan de acción 

src/app/modules/programacion/components/asignar-auditorias/modal-agregar-auditor/modal-agregar-auditor.component.html, src/app/modules/programacion/components/asignar-auditorias/modal-agregar-auditor/modal-agregar-auditor.component.ts, src/app/modules/programacion/components/auditorias-especiales/formulario-auditoria-especial/formulario-auditoria-especial.component.html, src/app/modules/programacion/components/auditorias-especiales/formulario-auditoria-especial/formulario-auditoria-especial.component.ts, src/app/modules/programacion/components/auditorias-especiales/registro-auditorias-especiales.component.html, src/app/modules/programacion/components/auditorias-especiales/registro-auditorias-especiales.component.ts, src/app/modules/programacion/components/consulta-plan-auditoria/consulta-plan-auditoria.component.html, src/app/modules/programacion/components/consulta-plan-auditoria/consulta-plan-auditoria.component.ts, src/app/modules/programacion/components/consulta-plan-auditoria/registrar-auditorias/add-auditoria-modal/add-auditoria-modal.component.html, src/app/modules/programacion/components/consulta-plan-auditoria/registrar-auditorias/add-auditoria-modal/add-auditoria-modal.component.ts, src/app/modules/programacion/components/consulta-plan-auditoria/registrar-auditorias/pdf-visualizador-modal/pdf-visualizador.component.ts, src/app/modules/programacion/components/consulta-plan-auditoria/registrar-auditorias/registrar-auditorias.component.html, src/app/modules/programacion/components/consulta-plan-auditoria/registrar-auditorias/registrar-auditorias.component.ts, src/app/modules/programacion/components/consulta-plan-auditoria/revision-jefe/pdf-visualizador/pdf-visualizador.component.ts, src/app/modules/programacion/components/consulta-plan-auditoria/revision-jefe/revision-jefe.component.html, src/app/modules/programacion/components/consulta-plan-auditoria/revision-jefe/revision-jefe.component.ts, src/app/modules/programacion/components/consulta-plan-auditoria/revision-secretario/modal-aprobacion-secretario/modal-aprobacion-secretario.component.html, src/app/modules/programacion/components/consulta-plan-auditoria/revision-secretario/modal-aprobacion-secretario/modal-aprobacion-secretario.component.ts, src/app/modules/programacion/components/consulta-plan-auditoria/revision-secretario/revision-secretario.component.html, src/app/modules/programacion/components/consulta-plan-auditoria/revision-secretario/revision-secretario.component.ts, src/app/shared/data/models/plan-anual-auditoria/plan-anual-auditoria.ts, src/app/shared/elements/components/cargar-archivo/cargar-archivo.component.html, src/app/shared/elements/components/cargar-archivo/cargar-archivo.component.ts, src/environments/environment.ts
udistrital/sisifo_documentacion#337
=> fix: Refactorización funciones del microcliente 

src/app/modules/programacion/components/asignar-auditorias/modal-agregar-auditor/modal-agregar-auditor.component.html, src/app/modules/programacion/components/asignar-auditorias/modal-agregar-auditor/modal-agregar-auditor.component.ts
udistrital/sisifo_documentacion#352
=> feat: Se agrega la asignacion y eliminacion de auditores 

src/app/modules/programacion/components/consulta-plan-auditoria/consulta-plan-auditoria.component.html, src/app/modules/programacion/components/consulta-plan-auditoria/registrar-auditorias/registrar-auditorias.component.html, src/app/modules/programacion/programacion.module.ts, src/app/shared/modules/iconos.module.ts, src/app/shared/shared.module.ts
udistrital/sisifo_documentacion#356
=> feat: Implementación botón de descarga de plantilla cargue masivo 

src/app/modules/programacion/components/asignar-auditorias/asignar-auditorias.component.html, src/app/modules/programacion/components/asignar-auditorias/asignar-auditorias.component.ts, src/app/modules/programacion/components/asignar-auditorias/tabla-consulta-auditorias/tabla-consulta-auditorias.component.html, src/app/modules/programacion/components/asignar-auditorias/tabla-consulta-auditorias/tabla-consulta-auditorias.component.spec.ts, src/app/modules/programacion/components/asignar-auditorias/tabla-consulta-auditorias/tabla-consulta-auditorias.component.ts, src/app/modules/programacion/components/asignar-auditorias/tabla-consulta-auditorias/tabla-consulta-auditorias.utilidades.ts, src/app/modules/programacion/programacion.module.ts
udistrital/sisifo_documentacion#357
=> feat: Se agrega la integracion de la consulta de auditorias y el modal de edicion

src/app/modules/planeacion/planeacion.module.ts, src/app/modules/programacion/components/asignar-auditorias/tabla-consulta-auditorias/tabla-consulta-auditorias.component.html, src/app/modules/programacion/components/auditorias-especiales/registro-auditorias-especiales.component.html, src/app/modules/programacion/components/consulta-plan-auditoria/registrar-auditorias/pdf-visualizador-modal/pdf-visualizador.component.css, src/app/modules/programacion/components/consulta-plan-auditoria/registrar-auditorias/pdf-visualizador-modal/pdf-visualizador.component.html, src/app/modules/programacion/components/consulta-plan-auditoria/registrar-auditorias/registrar-auditorias.component.html, src/app/modules/programacion/components/consulta-plan-auditoria/registrar-auditorias/registrar-auditorias.component.ts, src/app/modules/programacion/components/consulta-plan-auditoria/revision-jefe/pdf-visualizador/pdf-visualizador.component.css, src/app/modules/programacion/components/consulta-plan-auditoria/revision-jefe/pdf-visualizador/pdf-visualizador.component.html, src/app/modules/programacion/programacion.module.ts, src/app/shared/elements/components/cargar-archivo/cargar-archivo.component.ts, src/app/shared/pipes/unir-con-coma.pipe.spec.ts, src/app/shared/pipes/unir-con-coma.pipe.ts, src/app/shared/shared.module.ts, src/environments/environment.ts
udistrital/sisifo_documentacion#388
=> fix: ajuste generación de PDF de las auditorías 

src/app/modules/programacion/components/asignar-auditorias/modal-agregar-auditor/modal-agregar-auditor.component.ts, src/app/modules/programacion/components/auditorias-especiales/formulario-auditoria-especial/formulario-auditoria-especial.component.ts, src/app/shared/data/models/auditoria-auditor.ts
udistrital/sisifo_documentacion#390
=> feat: Se implementa la eliminación de los auditores asignados previamente en las auditorias 

src/app/modules/programacion/components/consulta-plan-auditoria/modal-ver-documentos-plan/modal-ver-documentos-plan.component.ts, src/app/modules/programacion/components/consulta-plan-auditoria/registrar-auditorias/pdf-visualizador-modal/pdf-visualizador.component.css, src/app/modules/programacion/components/consulta-plan-auditoria/registrar-auditorias/pdf-visualizador-modal/pdf-visualizador.component.html, src/app/modules/programacion/components/consulta-plan-auditoria/registrar-auditorias/pdf-visualizador-modal/pdf-visualizador.component.ts, src/app/modules/programacion/components/consulta-plan-auditoria/registrar-auditorias/registrar-auditorias.component.ts, src/app/modules/programacion/components/consulta-plan-auditoria/revision-jefe/revision-jefe.component.ts, src/app/modules/programacion/components/consulta-plan-auditoria/revision-secretario/revision-secretario.component.ts, src/app/shared/services/descarga.service.ts
udistrital/sisifo_documentacion#403
=> feat: Implementación servicio DescargaService y botón de descarga del PAA 

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/core/intercerptors/spinner.interceptor.ts, src/app/modules/planeacion/components/auditorias-internas/editar-auditoria/documentos-anexos-auditoria/documentos-anexos-auditoria.component.ts, src/app/modules/planeacion/components/auditorias-internas/editar-auditoria/editar-auditoria.component.ts, src/app/modules/programacion/components/asignar-auditorias/tabla-consulta-auditorias/tabla-consulta-auditorias.component.html, src/app/modules/programacion/components/asignar-auditorias/tabla-consulta-auditorias/tabla-consulta-auditorias.component.ts, src/app/modules/programacion/components/asignar-auditorias/tabla-consulta-auditorias/tabla-consulta-auditorias.utilidades.ts, src/app/modules/programacion/components/auditorias-especiales/registro-auditorias-especiales.component.html, src/app/modules/programacion/components/auditorias-especiales/registro-auditorias-especiales.component.ts, src/app/modules/programacion/components/consulta-plan-auditoria/consulta-plan-auditoria.component.ts, src/app/modules/programacion/components/consulta-plan-auditoria/modal-ver-documentos-plan/modal-ver-documentos-plan.component.ts, src/app/modules/programacion/components/consulta-plan-auditoria/registrar-auditorias/registrar-auditorias.component.html, src/app/modules/programacion/components/consulta-plan-auditoria/registrar-auditorias/registrar-auditorias.component.ts, src/app/shared/elements/components/spinner/spinner.component.html, src/app/shared/elements/components/spinner/spinner.component.ts, src/app/shared/pipes/unir-con-coma.pipe.ts, src/app/shared/services/spinner.service.ts, src/environments/environment.development.ts, src/environments/environment.ts
feat: udistrital/sisifo_documentacion#406 Refactorización de spinner para que no se oculte con la primera petición
=> feat: Refactorización de spinner para que no se oculte con la primera petición

src/app/core/services/oikos.service.ts, src/app/modules/planeacion/components/auditorias-internas/editar-auditoria/editar-auditoria.component.ts, src/environments/environment.ts
feat: udistrital/sisifo_documentacion#399 cargo de select dependencias
=> feat: Cargo de select dependencias

src/environments/environment.development.ts
feat: udistrital/sisifo_documentacion#399 variable de entorno oikos
=> feat: Variable de entorno oikos

src/app/modules/programacion/components/asignar-auditorias/tabla-consulta-auditorias/tabla-consulta-auditorias.component.html, src/app/modules/programacion/components/asignar-auditorias/tabla-consulta-auditorias/tabla-consulta-auditorias.component.ts
udistrital/sisifo_documentacion#402
=> fix: Se agrega la actualización de la tabla de consulta cuando se realiza un cambio en la auditoría 

src/app/modules/programacion/components/auditorias-especiales/registro-auditorias-especiales.component.ts
udistrital/sisifo_documentacion#407
=> fix: se corrige peticion para auditorias especiales

src/app/app-routing.module.ts, src/app/modules/planeacion/components/auditorias-internas/revision-documentos/revision-documentos.component.html, src/app/modules/planeacion/components/auditorias-internas/revision-documentos/revision-documentos.component.ts, src/app/modules/planeacion/components/auditorias-internas/tabla-auditorias-internas/tabla-auditorias-internas.component.ts, src/app/modules/programacion/programacion.module.ts, src/app/shared/shared.module.ts, src/environments/environment.ts
feat: udistrital/sisifo_documentacion#411 Revisión de documentos de auditoria y guardado de documento de plan de trabajo
=> feat: Revisión de documentos de auditoria y guardado de documento de plan de trabajo

src/app/modules/planeacion/components/auditorias-internas/tabla-auditorias-internas/tabla-auditorias-internas.utilidades.ts
=> feat: Información tabla auditores
